export const SET_NEW_USER = 'SET_NEW_USER'
export const SET_AUTH_USER = 'SET_AUTH_USER'
export const SET_TASKS = 'SET_TASKS'
export const SET_LAST_TASK_ID = 'SET_LAST_TASK_ID'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'